version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
  myapp:
    image: docker.io/bitnami/laravel:8
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
    #command: composer install
    #command: composer dump-autoload
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
